[GENERAL]
SIMILARITY_MEASURE = "cosine"
KEEP_ALIVE = "5m"

[MODELS.OPENAI]
API_KEY = false

[MODELS.GROQ]
API_KEY = false

[MODELS.ANTHROPIC]
API_KEY = false

[MODELS.GEMINI]
API_KEY = ""

[MODELS.CUSTOM_OPENAI]
API_KEY = false
API_URL = ""
MODEL_NAME = ""

[MODELS.OLLAMA]
API_URL = ""
API_KEY = false

[MODELS.DEEPSEEK]
API_KEY = false

[MODELS.AIMLAPI]
API_KEY = false

[MODELS.LM_STUDIO]
API_URL = ""

[MODELS.LEMONADE]
API_URL = ""
API_KEY = false

[API_ENDPOINTS]
SEARXNG = ""
